In [9]:
#!pip install ultralytics

   ---------------------------------------- 0.0/915.2 kB ? eta -:--:--
   ---------------------- ----------------- 524.3/915.2 kB 8.5 MB/s eta 0:00:01
   ---------------------- ----------------- 524.3/915.2 kB 8.5 MB/s eta 0:00:01
   ---------------------------------- ----- 786.4/915.2 kB 1.1 MB/s eta 0:00:01
   -------------------------------------- 915.2/915.2 kB 971.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/39.5 MB ? eta -:--:--
    --------------------------------------- 0.5/39.5 MB 5.6 MB/s eta 0:00:07
   - -------------------------------------- 1.0/39.5 MB 4.6 MB/s eta 0:00:09
   -- ------------------------------------- 2.9/39.5 MB 6.2 MB/s eta 0:00:06
   ----- ---------------------------------- 5.2/39.5 MB 7.2 MB/s eta 0:00:05
   -------- ------------------------------- 8.4/39.5 MB 9.3 MB/s eta 0:00:04
   ------------- -------------------------- 13.1/39.5 MB 11.7 MB/s eta 0:00:03
   ---------------- ----------------------- 16.8/39.5 MB 12.9 MB/s eta 0:00

만약 클래스(classes)를 json형태로 쓰면 int형이 아닌, str형으로 받아야한다.

In [5]:
from flask import Flask, request, jsonify
import os
from ultralytics import YOLO


app = Flask(__name__)

@app.route('/', methods=['GET'])
def home():
    return "hello world"

@app.route('/detect', methods=['POST'])
def detect():
    image = request.files['image']
    image_path = 'temp_image.jpg'
    image.save(image_path)

    model = YOLO('yolov8n.pt')
    result = model(image_path)
    detections = result[0].boxes.data.cpu().numpy()
    print(detections)

    result_json = []
    classes = [
    'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter',
    'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 
    'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 
    'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 
    'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 
    'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 
    'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 
    'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 
    'TV', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 
    'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 
    'scissors', 'teddy bear', 'hair drier', 'toothbrush'
    ]
    
    #for 문은 시퀀스, box의 0의 값이 coord에 종속되고, 플롯형이 됨, 이후 인덱스 0이 인덱스 box[:4]까지 반복
    for box in detections:
        result_json.append({
            'className': classes[int(box[5])],
            'bbox': [float(coord) for coord in box[:4]],
            'confidence': int(box[4])
        })
    
    return jsonify(result_json)
    
if __name__=='__main__':
    app.run(host='0.0.0.0', port=5001)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.0.217:5001
Press CTRL+C to quit




image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 4 persons, 1 car, 3 trucks, 1094.7ms
image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 4 persons, 1 car, 3 trucks, 904.1ms
Speed: 10.3ms preprocess, 1094.7ms inference, 31.9ms postprocess per image at shape (1, 3, 384, 640)
Speed: 199.2ms preprocess, 904.1ms inference, 32.6ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:25] "POST /detect HTTP/1.1" 200 -
127.0.0.1 - - [20/Feb/2025 18:00:25] "POST /detect HTTP/1.1" 200 -


[[     1291.5      568.77      1435.3      786.66      0.8842           0]
 [     60.267      563.74      210.83      799.24     0.86874           0]
 [     1580.6      569.74      1919.1      802.51     0.68851           7]
 [     504.66      590.54      823.92       804.9     0.59396           7]
 [     918.31      598.56      1202.9      799.73     0.49875           2]
 [     915.95      597.96      1201.6      799.82     0.49134           7]
 [     778.85       644.1      831.37      767.71     0.30214           0]
 [     934.38      886.62      1093.2      1076.7      0.2913           0]]
[[     1291.5      568.77      1435.3      786.66      0.8842           0]
 [     60.267      563.74      210.83      799.24     0.86874           0]
 [     1580.6      569.74      1919.1      802.51     0.68851           7]
 [     504.66      590.54      823.92       804.9     0.59396           7]
 [     918.31      598.56      1202.9      799.73     0.49875           2]
 [     915.95      597.9

127.0.0.1 - - [20/Feb/2025 18:00:25] "POST /detect HTTP/1.1" 200 -


[[     63.446      561.35       216.8      801.04      0.8761           0]
 [     1289.7      568.32      1429.3      785.06      0.8718           0]
 [     1576.5       567.1      1919.5      801.41     0.70924           7]
 [     505.82      588.55      828.49      804.19     0.58379           7]
 [      918.2      598.59      1201.3      797.44     0.53932           2]
 [      935.9      885.36      1094.4      1076.7     0.45894           0]
 [        916      598.09      1199.8      797.42     0.44959           7]
 [     949.43      885.45        1064      1069.1     0.33244           0]
 [     780.56      644.08      831.48      767.45     0.27448           0]]
image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 5 persons, 1 car, 3 trucks, 438.2ms
Speed: 5.0ms preprocess, 438.2ms inference, 28.1ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:25] "POST /detect HTTP/1.1" 200 -


[[     63.446      561.35       216.8      801.04      0.8761           0]
 [     1289.7      568.32      1429.3      785.06      0.8718           0]
 [     1576.5       567.1      1919.5      801.41     0.70924           7]
 [     505.82      588.55      828.49      804.19     0.58379           7]
 [      918.2      598.59      1201.3      797.44     0.53932           2]
 [      935.9      885.36      1094.4      1076.7     0.45894           0]
 [        916      598.09      1199.8      797.42     0.44959           7]
 [     949.43      885.45        1064      1069.1     0.33244           0]
 [     780.56      644.08      831.48      767.45     0.27448           0]]


image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 4 persons, 1 car, 2 trucks, 412.7ms
Speed: 6.1ms preprocess, 412.7ms inference, 27.2ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:26] "POST /detect HTTP/1.1" 200 -


[[     139.46         601      274.52      816.58     0.87147           0]
 [     1260.1      595.91      1389.9      797.23     0.80696           0]
 [     1532.1      592.52      1918.2      804.13     0.69881           7]
 [     917.48      625.14      1180.2      810.82     0.62874           2]
 [     548.66      622.74      834.02      816.87     0.59695           7]
 [      938.6      888.29      1090.8      1075.5     0.46029           0]
 [      800.2      671.02      839.99      782.02      0.2608           0]]
image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 4 persons, 1 car, 2 trucks, 428.6ms
Speed: 6.9ms preprocess, 428.6ms inference, 25.9ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:26] "POST /detect HTTP/1.1" 200 -


[[     139.46         601      274.52      816.58     0.87147           0]
 [     1260.1      595.91      1389.9      797.23     0.80696           0]
 [     1532.1      592.52      1918.2      804.13     0.69881           7]
 [     917.48      625.14      1180.2      810.82     0.62874           2]
 [     548.66      622.74      834.02      816.87     0.59695           7]
 [      938.6      888.29      1090.8      1075.5     0.46029           0]
 [      800.2      671.02      839.99      782.02      0.2608           0]]


image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 400.5ms
Speed: 4.2ms preprocess, 400.5ms inference, 29.3ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:27] "POST /detect HTTP/1.1" 200 -


[[     198.59      570.18       329.4      764.55     0.84901           0]
 [     1240.6      576.24      1364.4      761.84     0.84659           0]
 [     922.63      601.31      1161.2      772.79     0.72454           2]
 [     581.67      596.32       850.1      769.74      0.5024           2]
 [     580.46      596.32         849      769.23     0.44556           7]
 [     1500.2      582.47        1843      780.98     0.40634           7]]
image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 416.4ms
Speed: 4.7ms preprocess, 416.4ms inference, 23.1ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:27] "POST /detect HTTP/1.1" 200 -


[[     198.59      570.18       329.4      764.55     0.84901           0]
 [     1240.6      576.24      1364.4      761.84     0.84659           0]
 [     922.63      601.31      1161.2      772.79     0.72454           2]
 [     581.67      596.32       850.1      769.74      0.5024           2]
 [     580.46      596.32         849      769.23     0.44556           7]
 [     1500.2      582.47        1843      780.98     0.40634           7]]


image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 379.5ms
Speed: 4.3ms preprocess, 379.5ms inference, 23.8ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:28] "POST /detect HTTP/1.1" 200 -


[[      198.9      571.27      330.84      763.11     0.83547           0]
 [       1240      576.27      1364.8      763.54     0.81793           0]
 [     921.96      601.34      1161.6      772.59     0.72595           2]
 [     582.34      596.47      850.28      770.26     0.58477           2]
 [     1500.1       581.9      1840.4      780.95     0.42008           7]
 [     936.75      885.81      1094.4      1076.9     0.41219           0]
 [     581.08      595.54      849.41      768.67     0.39571           7]]
image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 412.6ms
Speed: 4.8ms preprocess, 412.6ms inference, 22.4ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:28] "POST /detect HTTP/1.1" 200 -


[[      198.9      571.27      330.84      763.11     0.83547           0]
 [       1240      576.27      1364.8      763.54     0.81793           0]
 [     921.96      601.34      1161.6      772.59     0.72595           2]
 [     582.34      596.47      850.28      770.26     0.58477           2]
 [     1500.1       581.9      1840.4      780.95     0.42008           7]
 [     936.75      885.81      1094.4      1076.9     0.41219           0]
 [     581.08      595.54      849.41      768.67     0.39571           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 261.7ms
Speed: 4.7ms preprocess, 261.7ms inference, 21.6ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:29] "POST /detect HTTP/1.1" 200 -


[[     1240.4       576.4      1364.3      761.98     0.85263           0]
 [     199.22      569.21      327.88      763.07     0.84222           0]
 [     922.14      600.45      1162.1       770.1     0.72656           2]
 [     582.93      594.83      849.96       769.2     0.51237           7]
 [     1501.5      580.22      1845.9      781.45      0.3629           7]
 [     1505.7      580.01      1839.8      778.53     0.33923           2]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 234.0ms
Speed: 4.4ms preprocess, 234.0ms inference, 16.3ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:29] "POST /detect HTTP/1.1" 200 -


[[     1240.4      576.97      1364.1      762.74     0.85529           0]
 [     198.76      569.78      327.74      764.99     0.84706           0]
 [        922      599.83      1161.6      771.14     0.67168           2]
 [     583.87       595.6      850.74      769.92     0.53756           2]
 [     582.23      595.54       849.6      769.16     0.41855           7]
 [     1499.9      581.07      1842.2      780.75      0.4003           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 1 car, 2 trucks, 226.9ms
Speed: 6.3ms preprocess, 226.9ms inference, 13.8ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:30] "POST /detect HTTP/1.1" 200 -


[[     1240.4      576.44        1364         764     0.84367           0]
 [     199.31      570.67      329.85       762.7     0.84275           0]
 [     922.08      600.66      1161.7      772.25     0.69451           2]
 [     581.82      595.48      849.78      770.16     0.55365           7]
 [     1498.5       580.8        1845      781.07     0.38097           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 252.2ms
Speed: 5.2ms preprocess, 252.2ms inference, 17.1ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:30] "POST /detect HTTP/1.1" 200 -


[[     198.87      570.78      330.74      762.56     0.84155           0]
 [     1239.9      576.71      1364.9      764.24     0.83791           0]
 [     920.85      600.38      1161.8       773.3        0.71           2]
 [     583.06       596.1      850.04      770.32     0.55021           2]
 [     581.44      595.84      849.19      769.68     0.46408           7]
 [     1499.3      581.12      1840.9      780.53     0.39327           7]
 [     938.71      885.58      1094.3      1076.9     0.27647           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 3 cars, 2 trucks, 250.5ms
Speed: 3.8ms preprocess, 250.5ms inference, 13.2ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:31] "POST /detect HTTP/1.1" 200 -


[[     1240.9      576.54      1363.5      764.89     0.85186           0]
 [     199.94      571.48      326.96      762.42     0.83067           0]
 [     919.59      601.12      1162.2       772.5      0.7551           2]
 [     581.53      596.24      848.33      771.68     0.52395           2]
 [     580.64      596.64      848.68      771.44     0.47092           7]
 [     1501.4      584.47      1918.7      783.63     0.37508           7]
 [     1503.6       582.5      1842.1      779.47     0.33453           2]
 [     931.99      886.55      1096.4      1079.6     0.27699           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 234.6ms
Speed: 4.9ms preprocess, 234.6ms inference, 14.2ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:32] "POST /detect HTTP/1.1" 200 -


[[        198      571.23      330.15      758.72     0.83207           0]
 [     1241.4      576.32      1364.4      764.15      0.8218           0]
 [     919.06      600.98      1161.7      772.85     0.67093           2]
 [     583.38      596.88      850.29      770.56     0.52379           2]
 [     581.73      596.54      849.06      770.29     0.47721           7]
 [     1499.9      582.32        1843      781.49     0.40179           7]
 [     936.53       885.5      1095.4        1077     0.32184           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 245.4ms
Speed: 4.9ms preprocess, 245.4ms inference, 13.7ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:34] "POST /detect HTTP/1.1" 200 -


[[     200.05      571.32      328.54      761.43     0.83672           0]
 [     1240.7      576.13      1364.4      765.69     0.82612           0]
 [     919.44      601.16        1162       772.7     0.77084           2]
 [     580.77      597.14      850.06      771.48     0.57522           2]
 [     579.72      596.06      849.04       770.4     0.40622           7]
 [     1501.1      581.23      1843.1      783.24     0.37861           7]
 [     937.54      887.71      1094.7      1076.9     0.26811           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 227.9ms
Speed: 5.1ms preprocess, 227.9ms inference, 13.3ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:35] "POST /detect HTTP/1.1" 200 -


[[     1240.4      576.33      1364.3      761.66     0.84109           0]
 [     198.92      569.25      326.54      764.79     0.83458           0]
 [     922.95      600.19      1161.6      770.42     0.67308           2]
 [     582.54      595.93      850.37      769.38     0.53067           2]
 [     581.66      595.71      849.88      769.85     0.44395           7]
 [       1504      580.24      1840.8      779.87     0.43389           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 3 cars, 1 truck, 235.0ms
Speed: 5.4ms preprocess, 235.0ms inference, 14.1ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:36] "POST /detect HTTP/1.1" 200 -


[[     1240.4      576.69      1364.5      762.04     0.86637           0]
 [     198.56      569.26      327.47      765.55     0.85005           0]
 [     922.92      600.05      1161.9      770.31     0.72122           2]
 [     582.34      595.58      850.35      769.44     0.52439           2]
 [     1504.7      580.59      1839.1       778.2        0.34           7]
 [       1502      580.37      1839.6         779     0.28707           2]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 1 car, 2 trucks, 239.2ms
Speed: 5.8ms preprocess, 239.2ms inference, 15.0ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:37] "POST /detect HTTP/1.1" 200 -


[[     198.92      570.69      329.63      759.96     0.83847           0]
 [     1240.4       576.2      1364.3      762.32     0.82872           0]
 [     922.01      600.78      1161.7      773.06     0.66182           2]
 [     583.03      596.64      849.94      770.35     0.52886           7]
 [     1500.4      581.18        1843      780.88     0.40753           7]
 [        940      885.79      1091.8      1076.7     0.38282           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 3 cars, 2 trucks, 241.7ms
Speed: 5.9ms preprocess, 241.7ms inference, 14.3ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:39] "POST /detect HTTP/1.1" 200 -


[[     1240.9      576.04      1364.1      764.85     0.82296           0]
 [     200.71         571      328.67      760.38      0.8118           0]
 [     920.24      601.73      1161.7      771.83      0.7471           2]
 [     581.08      596.91      849.73      771.19     0.52937           2]
 [     580.09      595.84      849.07      769.87     0.43274           7]
 [     1502.3      580.29      1841.4      780.94     0.39949           2]
 [     1503.6      580.37      1842.1      781.12     0.38039           7]
 [      938.6      887.28      1096.1        1077      0.2675           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 3 cars, 2 trucks, 243.8ms
Speed: 4.3ms preprocess, 243.8ms inference, 16.4ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:39] "POST /detect HTTP/1.1" 200 -


[[     1241.5       576.4      1363.7      764.52     0.84938           0]
 [     199.04       571.3      328.66      761.77     0.84484           0]
 [     921.92      600.95      1161.8      772.38     0.76508           2]
 [     581.61      597.12      849.68       771.5     0.55924           2]
 [     1501.2       583.9      1918.7      783.84     0.43408           7]
 [     580.29      596.89      848.71      771.21     0.41377           7]
 [     1503.8      581.56      1842.2      779.57     0.28894           2]
 [     939.04      886.59      1095.3      1076.6     0.26174           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 1 truck, 240.3ms
Speed: 4.0ms preprocess, 240.3ms inference, 15.5ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:40] "POST /detect HTTP/1.1" 200 -


[[     1241.1      576.73        1364      762.95     0.87111           0]
 [     199.47      568.78      328.74       763.5      0.8445           0]
 [     923.56      600.19        1162      770.18     0.71897           2]
 [     583.55      595.39      850.05      768.69     0.66659           2]
 [     1501.4      580.71        1846      781.91     0.40111           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 1 truck, 239.0ms
Speed: 4.7ms preprocess, 239.0ms inference, 16.5ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:41] "POST /detect HTTP/1.1" 200 -


[[       1241      576.26      1364.6      762.33     0.84745           0]
 [     198.87      569.33      327.91      762.34     0.83451           0]
 [     924.09      600.42      1161.5      770.97     0.67424           2]
 [     582.71      595.43      850.17      769.32     0.57076           2]
 [     1499.9      580.79      1844.5      780.97     0.42481           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 2 cars, 2 trucks, 239.4ms
Speed: 5.5ms preprocess, 239.4ms inference, 14.0ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:41] "POST /detect HTTP/1.1" 200 -


[[     198.59      570.37       329.2      763.42     0.84258           0]
 [     1240.7      576.07        1364      762.24     0.82838           0]
 [     922.91      600.78      1161.5      772.57     0.67733           2]
 [     582.29      595.63      849.89       769.9     0.49973           7]
 [     1500.2      581.63      1844.3      781.23     0.38974           7]
 [       1503      581.13      1841.8      780.63     0.32955           2]
 [     934.92      886.57      1092.8      1076.8     0.28679           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 3 cars, 2 trucks, 229.2ms
Speed: 4.6ms preprocess, 229.2ms inference, 21.2ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:42] "POST /detect HTTP/1.1" 200 -


[[     199.05      571.11      329.21      757.43     0.82676           0]
 [     1240.9      576.26      1364.5      764.73     0.81972           0]
 [     919.49      601.16      1161.7      772.97     0.70217           2]
 [     582.11       596.1      849.65       770.7     0.57653           2]
 [     937.93      885.61      1093.4        1077     0.41546           0]
 [     1499.3      581.46      1841.8      780.55     0.41082           7]
 [     580.61      594.78      848.88      769.36     0.40507           7]
 [     1501.7      580.76      1840.6      779.68     0.31744           2]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 274.9ms
Speed: 4.5ms preprocess, 274.9ms inference, 19.2ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:43] "POST /detect HTTP/1.1" 200 -


[[     1240.3       576.4      1364.4      762.17      0.8592           0]
 [      198.8      569.08      326.75      765.71     0.84286           0]
 [      922.8      600.15      1161.6      770.49     0.67942           2]
 [     582.16       595.9      850.35      769.62     0.52473           2]
 [     580.93      595.71       850.2      769.39     0.44709           7]
 [     1499.6      581.22      1844.7      780.59     0.38748           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 3 persons, 3 cars, 2 trucks, 229.2ms
Speed: 4.0ms preprocess, 229.2ms inference, 14.4ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:43] "POST /detect HTTP/1.1" 200 -


[[     1240.7      576.24      1364.1      764.99     0.83178           0]
 [     199.82      571.14      328.77      760.17     0.82781           0]
 [     919.35      601.79      1161.5      773.12     0.72404           2]
 [     583.07      596.66      850.08      771.11     0.57316           2]
 [     581.46      596.28      848.95      770.91     0.44403           7]
 [       1502      580.58      1841.1      780.85     0.37476           2]
 [     1499.2      581.35      1843.1      781.45     0.35699           7]
 [     934.81      885.89      1094.7      1077.2     0.33803           0]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 228.7ms
Speed: 3.8ms preprocess, 228.7ms inference, 14.5ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:44] "POST /detect HTTP/1.1" 200 -


[[     1240.4      576.46      1364.4      761.75      0.8604           0]
 [     198.77      568.79      328.17      763.06     0.84719           0]
 [     922.35      600.04        1162      770.01     0.71492           2]
 [     582.71      595.18      849.75      769.26     0.55887           2]
 [     581.62      595.33      849.52      769.74     0.42724           7]
 [     1500.1      579.71      1847.9      782.18     0.35471           7]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 3 cars, 1 truck, 282.4ms
Speed: 4.8ms preprocess, 282.4ms inference, 15.0ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:45] "POST /detect HTTP/1.1" 200 -


[[     1240.2      576.64      1364.3      762.51     0.86393           0]
 [     198.67       569.6       327.5      765.29     0.84184           0]
 [     922.96      600.14      1161.7       770.1     0.68678           2]
 [     583.34      595.21       850.7      769.75     0.55328           2]
 [     1498.8      580.24      1843.3      780.42     0.35919           7]
 [     1502.1      579.23      1842.5      779.72     0.28563           2]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 3 cars, 2 trucks, 228.1ms
Speed: 3.8ms preprocess, 228.1ms inference, 15.1ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:47] "POST /detect HTTP/1.1" 200 -


[[     198.88      570.41      328.91      763.07     0.83903           0]
 [     1240.9      576.23      1364.4      762.75     0.83185           0]
 [      922.2      600.97      1161.7      772.29     0.67869           2]
 [     582.27      595.22      850.04      769.96     0.54308           2]
 [     581.25      595.25      849.69      770.49     0.45385           7]
 [     1500.3      580.59      1846.1      781.36     0.40087           7]
 [     1503.1       579.9      1845.4      780.66     0.28736           2]]

image 1/1 c:\ws\HD_Rotem2_pycode\Day41\temp_image.jpg: 384x640 2 persons, 2 cars, 2 trucks, 237.6ms
Speed: 4.9ms preprocess, 237.6ms inference, 15.5ms postprocess per image at shape (1, 3, 384, 640)


127.0.0.1 - - [20/Feb/2025 18:00:48] "POST /detect HTTP/1.1" 200 -


[[     198.34      570.59      329.75      761.04     0.83593           0]
 [     1240.7      576.24      1364.3      764.21     0.82677           0]
 [     918.39      600.34      1161.6      773.27     0.66848           2]
 [     581.62      596.42      849.37      770.16     0.49892           7]
 [     583.03      596.94      850.62      770.71     0.48934           2]
 [     1500.3      581.94      1841.7      780.82      0.4065           7]]
